version: '3.7'
# The data processing is done on the host, see README.md

networks:
  proxy_net:
    name: proxy_net
    external: true
  matomo_network:
    name: matamo_network

services:
  app:
    build: ./build_context
    volumes:
      - ./matomo_app:/var/www/html
    links:
      - db
    environment:
      - VIRTUAL_HOST=${BASEURL}
      - VIRTUAL_PORT=8080
      - NETWORK_ACCESS=internal
      - LETSENCRYPT_HOST=${BASEURL}
      - LETSENCRYPT_MAIL=${MY_EMAIL}
      - MATOMO_DATABASE_HOST=db
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD=matomo
      - MYSQL_DATABASE=matomo
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      proxy_net:
        aliases:
          - matomo
      matomo_network:

  db:
    image: mariadb
    volumes:
      - ./matomo_data:/var/lib/mysql
    env_file:
      - ./.env
    command: --max-allowed-packet=64MB
    restart: unless-stopped
    networks:
      matomo_network:
        aliases:
          - db

